# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 978aae6cce4d01670fc79f89796afcec52c50edc7883cba6c7347c7f185e460a9736ed656b5a0f9d429bb3dc96dbf18f426e6f9feee439f5c86c5f8093a1a4af

test:
  secret_key_base: 9fc603b6c45ddf075e5876b442c7e8f13cc3d9ace3374cc5ac5d919c6a172b8a595c7c106762fda8769dc0c84cd4a7332579ad768b33e09e4c37867969706db3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
